### ISSUE TITLE
Proposed Reports

### ISSUE THREAD

**Issue by shelemiah** [ryanmitchell/ti-ext-reports#1]
Below is a list of suggested reports to further development of this extension.

- [ ] **Open Orders Summary**
       _Summary of in-complete/open orders over a selected period. Useful for pre-order forecasting for kitchen operations_
- [ ] **Average Prep. Time**
       _Snapshot of the average time it take to prepare an order over a selected period._
- [x] **Sales Overview**
      _Snapshot of key sales figures over a selected period. Example: Total Revenue, Total Orders, Total Meals, Total Pick-Up Orders, Total Delivery Orders, Total Cancelled Orders_
- [x] **Orders per Hour of the Day**
      _Revenue and number of orders per hour of the day over a selected period._
- [x] **Orders per Day of the Week**
     _Revenue and number of orders per day of the week over a selected period._
- [x] **Sales by Category**
     _Sales Revenue by categories over a selected period._
- [x] **Top 10 Customers**
      _List of top 10 customers based on customer spend for a a selected period._
- [x] **Top 10 Meal Items / Best Selling Products**
       _List the top 10 frequently ordered meal items for a selected period._
- [x] **Bottom 10 Customers**
      _List of bottom 10 customers based on customer spend over a a selected period. Possible a report to identify dormant/inactive customer accounts._
- [x] **Bottom 10 Meal Items / Worst Selling Products**
       _List of the 10 least ordered meal items over a selected period._
- [x] **Payment Method Report**
      _List of order volume by payment methods._

**Comment by ryanmitchell** [comment]
Ok, I've pushed some changes which handle most of the reports you have mentioned, I may do more later.

I've made it use blade too, which should make the view easier to style and layout. Would you be interested in helping with that side of things?

**Comment by shelemiah** [comment]
Thanks for a quick turnaround. I will make an attempt at layout and styling.
