### ISSUE TITLE
[Bug]: Builder.php L192

### ISSUE THREAD

**Issue by CupNoodles** [ryanmitchell/ti-ext-reports#11]
### What happened?

After default installation, clicking 'View' on the example Builder reports (and also 'Export CSV') throws this error

```
[2021-12-07 11:46:23] production.ERROR: TypeError: json_decode(): Argument #1 ($json) must be of type string, array given in /var/www/html/extensions/thoughtco/reports/controllers/Builder.php:169
```

I have a PR that fixes it for me, but fwiw I just installed this ext an hour ago and don't really know whats going on - possible that I've installed it wrong or that my myriad other extensions are causing a conflict, in which case please disregard!

### What did you expect to happen?

Would expect to be able to see the report! 

### Version

TI v3.2.0  Reports 2.0.2 (all on my dev docker which is pretty cluttered tbh)

### What browser are you seeing the problem on?

Firefox

**Comment by ryanmitchell** [comment]
I think the issue here is my data seed in the migration is wrong - I've fixed it up in https://github.com/ryanmitchell/ti-ext-reports/commit/10108083dd41b9cda88842d07d2cac34fa0a1da9
