### ISSUE TITLE
Some orders for a day are ignored/skipped for some stats computation

### ISSUE THREAD

**Issue by BreakSecurity** [ryanmitchell/ti-ext-reports#4]
**Expected Behaviour**
The report should count correctly all orders for a day.

**Actual behaviour**
The report does not count all the orders of a day (or a time interval), but it ignores some of these for reasons unknown to me...
These are a part of the November 21 orders taken from the order list, listed in descending order of price
![immagine](https://user-images.githubusercontent.com/38836022/101056932-c793a380-358b-11eb-8c66-66776681ec6b.png)

This is the November 21 report page; the different widgets at the top are almost entirely right (the only problem is that cancelled orders are not counted). 
![immagine](https://user-images.githubusercontent.com/38836022/101056950-ce221b00-358b-11eb-9ca3-b8b3f7dae6f2.png)

Moreover, the "Top Customers" list is not correct as some of the orders in the list (see the first image) are not counted. While in the order list there is an order of 95 euros, one of 86 euros, one of 63 euros and one of 55 euros (etc), in the report there is the first order of 95 euros and then the second is directly the 55 one. 
![immagine](https://user-images.githubusercontent.com/38836022/101056984-d5e1bf80-358b-11eb-8d5a-673bf4541091.png)

This also happens for longer time intervals: in general, some orders are not considered in the "Top Customers" list (while they are correctly counted by the widgets above).
Similarly, in the "Bottom Customers" list a series of orders are listed, all bearing the figure € 0.00; the point is that these orders took place on other days and were not null.
![immagine](https://user-images.githubusercontent.com/38836022/101057018-dda16400-358b-11eb-89d8-55135d29d46e.png)

**Version**
v.3.0.4-beta.24.4 and last report vers

**Comment by ryanmitchell** [comment]
I've tweaked the query a bit which should cover the date range and cancelled issues, let me know if not.
https://github.com/ryanmitchell/ti-ext-reports/commits/master

Bottom customers includes customer that have not ordered in the time period - thats by design as it helps identify dormant customer accounts.

**Comment by BreakSecurity** [comment]
I will test and report back to you

**Comment by BreakSecurity** [comment]
Negative order OK
Still missing same orders on top customer list...

**Comment by ryanmitchell** [comment]
Cant see any reason for orders not to be included other than by status - only counting completed and cancelled orders. Might that be the reason?

**Comment by BreakSecurity** [comment]
Ok it was even simpler it only counts registered users

**Comment by ryanmitchell** [comment]
Hmm yeah it does pull from customers. I suppose I could do it another way but I’ll need to think it out. 

Going to change how the extension works anyway so lots to be done.

**Comment by BreakSecurity** [comment]
Wanna tell more about those changes?

**Comment by ryanmitchell** [comment]
When I’m done!

**Comment by BreakSecurity** [comment]
Solved

**Comment by ryanmitchell** [comment]
Just pushed a load of updates to make it use widgets like the dashboard.

**Comment by BreakSecurity** [comment]
Good looking to me except for date range with the awkward context filed. Would be useful to have like in dashboard of tasty different views and settings per users and permission to avoid some users to change settings.

**Comment by ryanmitchell** [comment]
Not sure what you mean by this.

**Comment by BreakSecurity** [comment]
If I want User A & User B to see different widgets, and only user A can modify the dashboard

**Comment by ryanmitchell** [comment]
Yeah not supported (yet).

**Comment by BreakSecurity** [comment]
Total Sales: works but do NOT subtract cancelled orders
Total Orders: works but do NOT subtract cancelled orders
Total Items: do NOT count items
Total pickup: do NOT work
Total delivery: count well but do NOT subtract cancelled orders
Cancelled order: GOOD!

**Comment by BreakSecurity** [comment]
![immagine](https://user-images.githubusercontent.com/38836022/101348086-615c9880-388b-11eb-95d5-2bbe75906958.png)
Maybe can help you visualize what I have done better

**Comment by ryanmitchell** [comment]
Thanks, pushed an update with fixes

**Comment by BreakSecurity** [comment]
Total Sales: OK
Total Orders: OK
Total Pickups: OK
Total Deliveries: OK
Total Cancelled: OK
Total Items:
1) Do NOT exclude cancelled orders from the count
2) Ignore multiple products in the same order (ex. if I buy 10 sandwich within one order it counts sandwich 1x)

**Comment by ryanmitchell** [comment]
Thats what I intend total items to be - the number of different line items purchased, not the total number of items.

**Comment by BreakSecurity** [comment]
Got it so only different type of product and NOT quantity. Can I ask you why do you prefer in this way?

**Comment by ryanmitchell** [comment]
I’m just making up stats I think are useful :)

**Comment by BreakSecurity** [comment]
Perfect :) Just want to know. Also it do not remove cancelled orders from the line items count

**Comment by ryanmitchell** [comment]
I know, I think I’m happy enough to leave it being counted.

Can always add another stat for what you are wanting, its easily done with the new widget format.

I may end up abandoning the extension and making it part of the main dash.

**Comment by BreakSecurity** [comment]
I think that can be part of main dash too. I close this thanks for all the great stuff as always
