### ISSUE TITLE
Extra report (amount of order per city)

### ISSUE THREAD

**Issue by diverds1992** [ryanmitchell/ti-ext-reports#6]
Maybe it's a nice idea to have an extra filter like the "top customers" but then with city's where you deliver

So like
City A 10 orders
City B 5 orders
etc
etc

So you have a nice overview of the city where you Deliver and where you can use a bit more promotion

**Comment by ryanmitchell** [comment]
Yep. My plan would be to allow a view to drill down into the data and group orders so you can make custom queries... just need to get some time to work on it :)
